### ISSUE TITLE
BEDTabix class missing

### ISSUE THREAD

**Issue by GreenInnovator** [elsiklab/gwasviewer#2]
I can't load the plugin.The default Jbrowse does'nt have 
"storeClass" : "JBrowse/Store/SeqFeature/BEDTabix"

Where can I get this? Thx

**Comment by cmdcolin** [comment]
It is true that BEDTabix hasn't been merged yet, it is waiting on this pull request https://github.com/GMOD/jbrowse/pull/729

You could try checking out that pull request, or you can also load your track with flatfile-to-json.pl as the alternative to BEDTabix

I simply like BEDTabix because it easily expresses the type of data that GWASViewer needs

I updated the README to have an example configuration for a track that was loaded with flatfile-to-json.pl

**Comment by cmdcolin** [comment]
Feel free to let me know if there are any more issues with this! Will wait on bedtabix mergers
